### ISSUE TITLE
Could you please give an instruction about deploying on any other cloud server?

### ISSUE THREAD

**Issue by titusbiao** [abskmj/youtube-hls-m3u8#10]
Hello abskmj,

The  repository Youtube-HLS-m3u8 is very good, and help me a lot when using the ythls.onrender.com permanent link. As you said, it would be better to deply it on other cloud server in order to save resources to onrender.com. 

Could you please give out guides or instructions for the deployment? Such as, when we get a new Linux server from any cloud provider, any commands need to input? any prerequirement libraries need to install? or using any docker image environment?

Many thanks,

**Comment by abskmj** [comment]
Hello, thanks for your appreciation. Any developer with basic understanding of Nodejs should be able to deploy this service.

I'm planning to start a paid integration / deployment service to support this project.  If anyone is interested, please drop a comment.
