### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LeBazarDeBryan** [abskmj/youtube-hls-m3u8#11]
The website is not working, i get the error "Internal Server Error" with this link: https://ythls.onrender.com/video/5mGuCdlCcNM.m3u8

YouTube link: https://www.youtube.com/watch?v=5mGuCdlCcNM

**Comment by abskmj** [comment]
The service is limited to live videos.

**Comment by LeBazarDeBryan** [comment]
> The service is limited to live videos.

Okay, thanks for replying.
