### ISSUE TITLE
Fixed stream quality

### ISSUE THREAD

**Issue by thegamerguy925** [abskmj/youtube-hls-m3u8#13]
Hey,

Is there any way to keep a fixed stream quality?? I'm setting it up on my Android TV, but don't have much of internet bandwidth to run streams on 1080p or 720p, so I'd like it to run on a fixed 480p. Is it possible??

**Comment by abskmj** [comment]
The service currently doesn't support selecting the stream quality. However, it might be possible technically and needs additional compute and memory resources on the server.

**Comment by alpgulmez** [comment]
> Hey,
> 
> Is there any way to keep a fixed stream quality?? I'm setting it up on my Android TV, but don't have much of internet bandwidth to run streams on 1080p or 720p, so I'd like it to run on a fixed 480p. Is it possible??

Yes its avaliable. Just copy the live stream url and paste on your browser. Open downloaded file with Notepad. And now you can see and select qualities.
I'm trying to find how can getting stream code in normal videos :D
