### ISSUE TITLE
Some channel id not working

### ISSUE THREAD

**Issue by empirezeus** [abskmj/youtube-hls-m3u8#21]
I am trying to test channel id: UCKL5hAuzgFQsyrsQKgU0Qng via vlc using https://ythls-v2.onrender.com/channel/$youtube_channel_id.m3u8 , unfortunately vlc just force stop the programs automatically, the channel has only 1 live video same with channel id: UCstEtN0pgOmCf02EdXsGChw

**Comment by abskmj** [comment]
Can you open the link on the browser and see what error is shown? I see the channel is not live all the time.

**Comment by empirezeus** [comment]
> Can you open the link on the browser and see what error is shown? I see the channel is not live all the time.

https://www.youtube.com/@gmanetwork

https://www.youtube.com/@abscbnentertainment

This are the links i wanted to try and using their channel id

**Comment by abskmj** [comment]
Thanks for the links. I have updated the server. These should be working now.

**Comment by empirezeus** [comment]
Thank you so much tested working

**Comment by empirezeus** [comment]
btw i also notice its not working in this page https://www.youtube.com/@ALLTHEKPOP with id: UCPde4guD9yFBRzkxk2PatoA

**Comment by empirezeus** [comment]
Stream lost again, cannot stream both 2 programs which are playing earlier wondering what happen

**Comment by abskmj** [comment]
The service is sometimes unstable due to large number of user requests.

**Comment by empirezeus** [comment]
Noted thank you so much!

**Comment by empirezeus** [comment]
will just observe channel id UCstEtN0pgOmCf02EdXsGChw if its stable since thats the only one not working. thank you!
