### ISSUE TITLE
Service is suspended

### ISSUE THREAD

**Issue by ibrahimazam11** [abskmj/youtube-hls-m3u8#24]
How to test the executable? Currently the server is not responding and showing the attached error. 
https://ythls-v2.onrender.com/
"This service has been suspended by its owner."

![image](https://github.com/abskmj/youtube-hls-m3u8/assets/34368826/f6fd48d2-1c62-40aa-b2b6-ce0de1045e06)

**Comment by abskmj** [comment]
The service has hit the limits of the basic tier and the cloud provider has suspended the service for this month. Please check at the start of next month.

**Comment by Qoraiche** [comment]
> The service has hit the limits of the basic tier and the cloud provider has suspended the service for this month. Please check at the start of next month.

Hi @abskmj,
i can provide you with a premium server to host your service if you want to, reach me at ilovemaroc123[at]gmail[dot]com
