### ISSUE TITLE
[Question] Source Code

### ISSUE THREAD

**Issue by ramazansancar** [abskmj/youtube-hls-m3u8#25]
Alternative proxies can be created if you can share the source code. (If there is Docker, Kubernetes etc., I think a lot of people will use it.)

In fact, as in other open resources, resource consumption can be maintained in a shared manner by looking at uptime records and determining the most stable ones and recommending them.

**Comment by abskmj** [comment]
Hello, thanks for the suggestion. The server executable is available for purchase (mainly to support this project).

**Comment by ramazansancar** [comment]
For example, it could be like here:
https://uptime.invidious.io/

https://docs.invidious.io/instances/
