### ISSUE TITLE
Stream URL not found

### ISSUE THREAD

**Issue by alexavil** [abskmj/youtube-hls-m3u8#26]
When trying to use the `https://ythls-v3.onrender.com/` link on any working stream, it replies with `{"message":"stream url not found"}` instead of the `*.m3u8`.

https://www.youtube.com/watch?v=HfgIFGbdGJ0 - this stream is currently up
but https://ythls-v3.onrender.com/video/HfgIFGbdGJ0.m3u8 fails

**Comment by abskmj** [comment]
The cloud provider has permanently stopped all outgoing requests to youtube due to very high traffic.

**Comment by ramazansancar** [comment]
Continuing the project with the multi-source as suggested by me will both reduce the main server traffic and provide an alternative thanks to the supporters. @abskmj 
https://github.com/abskmj/youtube-hls-m3u8/issues/25

**Comment by abskmj** [comment]
The service is back online
