### ISSUE TITLE
Trying with an video is not working

### ISSUE THREAD

**Issue by thomraider12** [abskmj/youtube-hls-m3u8#27]
I tried obtaining a live stream that's from a channel that has multiple streams. If I enter the link of any video, it'll get me this error:

`{"message":"Youtube HLS Server is running, details on how to use it at https://github.com/abskmj/iptv-youtube-live"}`
This occurs with any video/live.

**Comment by abskmj** [comment]
The video links are currently disabled on the public server due to high volume of requests. The channel links are active.
